FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Restaurants/DiningHall/DiningHall.csproj", "DiningHall/"]
RUN dotnet restore "Restaurants/DiningHall/DiningHall.csproj"
COPY . .
WORKDIR "/src/DiningHall"
RUN dotnet build "DiningHall.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DiningHall.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DiningHall.dll"]
